### ISSUE TITLE
Should indirect mob kills be counted?

### ISSUE THREAD

**Issue by pandapaul** [ToroCraft/Dailies#45]
Source:  https://minecraft.curseforge.com/projects/baileys-dailies?comment=46

I'm thinking I prefer that kill counting stay as it is for simplicity etc, but I'm curious for comments from the team.  I'm guessing that the event we're listening to triggers on direct kill, but I haven't looked into it.

**Comment by zeriley** [comment]
I don't know that it's possible.  Or at least easily possible.  There are death messages, though, that seem to know indirect kills.  Like "[player] was doomed to fall to death by [other player]" or "[player] burned in lava while escaping [other player]" so maybe if we can find that logic and implement it similarly.  It is frustrating to complete the quests when you use a flame bow or fire aspect sword.

**Comment by pandapaul** [comment]
Ah ok yeah.  If flame weapons are getting in the way of getting the kills that is definitely frustrating.

**Comment by frodare** [comment]
I think it is a good idea.  It probably wouldn't be too bad.  We could listen to a event triggered when entities are hurt and add at tag to the entity for the right conditions.  Then on the death event we could check if any tags were added and give out credit appropriately.  We should probably add in a time stamp to so that the tags could time out.

**Comment by pandapaul** [comment]
Great feedback @zeriley and @frodare .  Going to close this issue and create one to make it happen.
