### ISSUE TITLE
Bailey dailies is offline...

### ISSUE THREAD

**Issue by Kaisoul** [ToroCraft/Dailies#55]
The quest server seems to be offline for at least 5 hours as of me writing this...  figure i would make a post just in case.

http://www.minecraftdailies.com/  also did not show the daily quests for the day.
Also there was no offline quests when i logged into the game.

**Comment by pandapaul** [comment]
Yeah there was some kind of database connection problem.  Alerts need to be added so that outages can be handled more promptly in the future.  Here's an issue that will track that work:  https://github.com/pandapaul/minecraft-dailies-server/issues/32  

Hopefully the database connection problem in question doesn't occur again.  As far as I know, we haven't had an outage since the Mongoose version was upgraded.  :crossed_fingers:
